#!/bin/bash

branches=`git for-each-ref --format='%(refname:short)' "refs/heads/*"`

compare_to="master"  # make this changeable later

for branch in $branches; do
    comparison=`git rev-list --left-right --count ${compare_to}...${branch}`
    echo "$comparison $branch"
done
