#!/bin/bash
# NOTE: Sorry, I don't think that sh will cut it for this one (use of shopt
# command)

# dotsbu
# A script to back up the dot-files and dot-directories.
#
# USAGE: 
#        dotsbu
####later usage ideas: dotsbu [-tzs] [DIRECTORY] [FILENAME]
####later adding:  choose a directory to back up the dotfiles from
####               pick a filename
####               choose compression choices

wasenabled=`shopt -q dotglob`
shopt -s dotglob
outdir="dots"

for afile in .*
do
   [ "$afile" = ".." ] || [ "$afile" = "." ] || cp -R $afile $outdir
done

#if [!wasenabled]
#then
    shopt -u dotglob
#    echo "turning off dotglob"
#fi
