#!/usr/bin/env python

import configparser
import os
import pathlib
import webbrowser

def get_account(config, profile_name):
    return config[f"profile {profile_name}"]["sso_account_id"]

def get_role(config, profile_name):
    return config[f"profile {profile_name}"]["sso_role_name"]

def get_url_base(config, profile_name):
    session = config[f"profile {profile_name}"]["sso_session"]
    return config[f"sso-session {session}"]["sso_start_url"]

def load_config():
    config_file = str(pathlib.Path.home() / ".aws/config")
    config = configparser.RawConfigParser()
    config.read(config_file)
    return config

if __name__ == "__main__":
    profile_name = os.environ.get("AWS_DEFAULT_PROFILE")
    config = load_config()
    account = get_account(config, profile_name)
    role = get_role(config, profile_name)
    url_base = get_url_base(config, profile_name)
    url = f"{url_base}/console?account_id={account}&role_name={role}"
    webbrowser.open(url)
