#!/usr/bin/env python

from datetime import datetime, timezone, timedelta
import argparse

def parse():
    parser = argparse.ArgumentParser()
    parser.add_argument('hours', type=int)
    return parser.parse_args()

DATE = "%a %d %b"
TIME = "%H:%M"


# TODO: make both messages available via a flag

# this is the message I use when I think a review is unlikely, or when I
# may need feedback from multiple people (bigger changes)
MSG = (
    "This is ready for review and comment. "
    "I will leave it open for at least {hours} hours, "
    "merging no earlier than {datestring}."
)

# this is the message when I just want to give a reasonable amount of time
# for a review to occur (smaller changes)
MSG = (
    "This is ready for review and comment. "
    "Without review, I will merge this after at least {hours} hours, "
    "no sooner than {datestring}."
)

def main(hours):
    now = datetime.now(timezone.utc)
    round_down = now.replace(minute=0, second=0, microsecond=0)
    round_up = round_down + timedelta(hours=1)
    delta = timedelta(hours=hours)
    result_utc = round_up + delta
    result_local = result_utc.astimezone()
    if result_local.day != result_utc.day:
        LOCAL_DATE = "%a %d %b "
    else:
        LOCAL_DATE = ""

    datestring = (
        "{utc_date} {utc_time} GMT "
        "({local_date}{local_time} my local)".format(
            utc_date=result_utc.strftime(DATE),
            utc_time=result_utc.strftime(TIME),
            local_date=result_local.strftime(LOCAL_DATE),
            local_time=result_local.strftime(TIME),
        )
    )
    print(MSG.format(hours=hours, datestring=datestring))

if __name__ == "__main__":
    opts = parse()
    main(opts.hours)
