#!/usr/bin/env python

from datetime import datetime, timezone, timedelta
import argparse

def parse():
    parser = argparse.ArgumentParser()
    parser.add_argument('hours', type=int)
    return parser.parse_args()

DATE = "%a %d %b"
TIME = "%H:%M"


MSG = (
    "This is ready for review and comment. "
    "I'll leave it up for at least {hours} hours. "
    "Will merge no earlier than {datestring}."
)


def main(hours):
    # TODO: this could be made more fancy to handle cases where GMT changes
    # the day, but as long as I'm in GMT+1/+2, I won't bother
    now = datetime.now(timezone.utc)
    round_down = now.replace(minute=0, second=0, microsecond=0)
    round_up = round_down + timedelta(hours=1)
    delta = timedelta(hours=hours)
    result_utc = round_up + delta
    result_local = result_utc.astimezone()
    datestring = "{local_date} {local_time} ({utc_time} GMT)".format(
        local_date=result_local.strftime(DATE),
        local_time=result_local.strftime(TIME),
        utc_time=result_utc.strftime(TIME)
    )
    print(MSG.format(hours=hours, datestring=datestring))

if __name__ == "__main__":
    opts = parse()
    main(opts.hours)
