#!/bin/sh

# I have my own pseudo-markdown syntax, and this converts it into Pandoc
# Markdoc for subsequent parsing

#############################################################################
# Following TeX, I use `` and '' for quotes. The backtick-escaped code
# blocks delimited by `` in Markdown are now delimited by ```.

# For now, we leave a single backtick to delimit a code block. Eventually,
# we'll want to allow single-quote as well.

sed 's/\`\`\([^\`]\)/\&ldquo;\1/g' |
sed "s/\'\'/\&rdquo;/g" |
sed 's/\`\`\`/\`\`/g'

#############################################################################

