#!/bin/bash

mydir=`pwd`
osascript  -e 'tell application "Terminal"' \
  -e 'tell application "System Events" to tell process "Terminal" to keystroke "t" using command down' \
  -e "do script with command \"cd ${mydir}\" in window 1" \
  -e 'end tell'

