#!bin/bash

function docview
{
# define $file, $extension, $base
   for file in $@
   do
       base=`echo $file | sed 's/\(.*\)\.\(.*\)/\1/'`
       ext=`echo $file | sed 's/\(.*\)\.\(.*\)/\2/'`

       if [ $extension="pdf" ]
       then
          `open -a Preview ${base}.pdf`
       elif [ $extension="dvi" ]
       then
          `dvipdfm ${base}.dvi`
          docview ${base}.pdf
       elif [ $extension="tex" ]
       then
          `tex ${base}.tex`
          `docview ${base}.dvi`
       fi
   done
       
   # tex -> dvi -> pdf -> Preview.app
   # dvi -> pdf -> Preview.app
   # pdf -> Preview.app
}
